//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class atenciondetalle
    {
        public int idADetalle { get; set; }
        public bool estado { get; set; }
        public int idAtencion { get; set; }
        public int idEmpleado { get; set; }
    
        public virtual atencion atencion { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
