//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class diapatronal
    {
        public int idDiaPatronal { get; set; }
        public System.DateTime dia { get; set; }
        public int idCiudad { get; set; }
    
        public virtual ciudad ciudad { get; set; }
    }
}
