//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class horarioextra
    {
        public int id { get; set; }
        public Nullable<double> horas { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string comentarios { get; set; }
        public int idTipoHora { get; set; }
        public int idEmpleado { get; set; }
        public int idPlanilla { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual planilla planilla { get; set; }
        public virtual tipohora tipohora { get; set; }
    }
}
