//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioExtra
    {
        public int id { get; set; }
        public System.TimeSpan horaInicio { get; set; }
        public System.TimeSpan horaFinal { get; set; }
        public string comentarios { get; set; }
        public System.DateTime fecha { get; set; }
        public int idTipoHora { get; set; }
        public int idEmpleado { get; set; }
        public int idPlanilla { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Planilla Planilla { get; set; }
        public virtual tipoHora tipoHora { get; set; }
    }
}
