//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class horariosucursal
    {
        public int idHSucursal { get; set; }
        public string dias { get; set; }
        public string aperturas { get; set; }
        public string cierres { get; set; }
        public int idSucursal { get; set; }
    
        public virtual sucursal sucursal { get; set; }
    }
}
