//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sBanBan : DbContext
    {
        public sBanBan()
            : base("name=sBanBan")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<atencion> atencion { get; set; }
        public virtual DbSet<atenciondetalle> atenciondetalle { get; set; }
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<comentariosplanilla> comentariosplanilla { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<descuentos> descuentos { get; set; }
        public virtual DbSet<dianacional> dianacional { get; set; }
        public virtual DbSet<diapatronal> diapatronal { get; set; }
        public virtual DbSet<dispositivo> dispositivo { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<fiestanacional> fiestanacional { get; set; }
        public virtual DbSet<hangar> hangar { get; set; }
        public virtual DbSet<horario> horario { get; set; }
        public virtual DbSet<horarioextra> horarioextra { get; set; }
        public virtual DbSet<horariosucursal> horariosucursal { get; set; }
        public virtual DbSet<planilla> planilla { get; set; }
        public virtual DbSet<planillahorario> planillahorario { get; set; }
        public virtual DbSet<registrosalarial> registrosalarial { get; set; }
        public virtual DbSet<sistemapension> sistemapension { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<telefono> telefono { get; set; }
        public virtual DbSet<tipohora> tipohora { get; set; }
        public virtual DbSet<tipousuario> tipousuario { get; set; }
        public virtual DbSet<trabajo> trabajo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
