//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sBanBan : DbContext
    {
        public sBanBan()
            : base("name=sBanBan")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atencion> Atencion { get; set; }
        public virtual DbSet<AtencionDetalle> AtencionDetalle { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<ComentariosPlanilla> ComentariosPlanilla { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Descuentos> Descuentos { get; set; }
        public virtual DbSet<DiaNacional> DiaNacional { get; set; }
        public virtual DbSet<DiaPatronal> DiaPatronal { get; set; }
        public virtual DbSet<Dispositivo> Dispositivo { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<HorarioExtra> HorarioExtra { get; set; }
        public virtual DbSet<Planilla> Planilla { get; set; }
        public virtual DbSet<PlanillaHorario> PlanillaHorario { get; set; }
        public virtual DbSet<RegistroSalarial> RegistroSalarial { get; set; }
        public virtual DbSet<SistemaPension> SistemaPension { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Telefono> Telefono { get; set; }
        public virtual DbSet<tipoHora> tipoHora { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Trabajo> Trabajo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
