//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefono
    {
        public int idTelefono { get; set; }
        public int idEmpleado { get; set; }
        public string telefono1 { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
