//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int idUsuario { get; set; }
        public string usuario1 { get; set; }
        public string contrasena { get; set; }
        public bool reseteo { get; set; }
        public int idEmpleado { get; set; }
        public int idTipo { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual tipousuario tipousuario { get; set; }
    }
}
