//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBanHorasExtra
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sbanbanHE : DbContext
    {
        public sbanbanHE()
            : base("name=sbanbanHE")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<descuentos> descuentos { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<horario> horario { get; set; }
        public virtual DbSet<horarioextra> horarioextra { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<trabajo> trabajo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
